[production]
phpSettings.display_startup_errors = 0
phpSettings.display_errors = 0
includePaths.library = APPLICATION_PATH "/../library"
bootstrap.path = APPLICATION_PATH "/Bootstrap.php"
bootstrap.class = "Bootstrap"
appnamespace = "Application"
resources.frontController.controllerDirectory = APPLICATION_PATH "/controllers"
resources.frontController.params.displayExceptions = 0
resources.view[] =

resources.layout.layoutPath = APPLICATION_PATH "/layouts/scripts/"
resources.db.adapter = "PDO_SQLITE"
resources.db.params.dbname = APPLICATION_PATH /../data/db/guestbook.db
[staging : production]

[testing : production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1

resources.db.adapter = "PDO_SQLITE"
resources.db.params.dbname = APPLICATION_PATH /../data/db/guestbook-testing.db
[development : production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1
resources.frontController.params.displayExceptions = 1

resources.db.adapter = "PDO_SQLITE"
resources.db.params.dbname = ../data/db/guestbook-dev.db

# 以下にAPPLICATION_PATHがあると、Zend/Db/Adapter/Pdo/Abstract.phpの124行目でエラーになります
#resources.db.params.dbname = APPLICATION_PATH /../data/db/guestbook-dev.db 
#resources.db.params.dbname = d:/src/zfTest/data/db/guestbook-dev.db        # これでも正常に動作します。
